((nil . ((cmake-ide-project-dir . "/Users/mac/Workspace/uv/ebus")
         (cmake-ide-build-dir . "/Users/mac/Workspace/uv/ebus/build")
	 (projectile-project-name . "ebus")
	 (projectile-project-run-cmd . "./build/ebus")
	 )))
